### ISSUE TITLE
close display for robothor

### ISSUE THREAD

**Issue by GracefulMan** [allenai/allenact#257]
how can i close the display of unity, since it will create many display window when training!

**Comment by Lucaweihs** [comment]
Hi Hongying, 

Unfortunately I don't think this is currently possible as Unity needs to render to a display when training. Unity does have a `-batchmode` option that allows for running without a display but some preliminary testing by me suggests that the images it returns when using this mode are blank. @ekolve would you know of workaround so that things don't get cluttered? One (slighly hacky): depending on your OS would it be possible to start training in its own separate screen/workspace so that all of the unity windows have their dedicated area?

**Comment by ekolve** [comment]
Could you tell me what platform you are on?

**Comment by GracefulMan** [comment]
I run the code on ubuntu 20.04, it will open many unity window.

**Comment by GracefulMan** [comment]
i want to know whether it will delay the trainning process? now there are a lot of display window when train the agent.

**Comment by Lucaweihs** [comment]
Hi Hongying, it shouldn't have a large impact on the training speed. If you tell me about your computer's hardware (# processes + # gpus) I should be able to give you a ballpark figure of what FPS you should be seeing during training (the FPS is printed every time AllenAct logs training metrics / losses).

**Comment by GracefulMan** [comment]
Hi, my hardware information:
Processor: Intel® Core™ i7-8700K CPU @ 3.70GHz × 12 
Graphics: NVIDIA Corporation TU104 [GeForce RTX 2080] , only 1 GPU.
the command is from tutorial:

```bash
python main.py object_nav_ithor_ppo_one_object -b projects/tutorials -o one_ppo
``` 
the following is screenshot when run the command:

![](https://i.ibb.co/QvTyQ85/Screenshot-2021-03-05-15-51-11.png)

**Comment by ekolve** [comment]
Run the following from the shell:

```
sudo apt-get install xdotool
```

Then run the following script after starting your training process:
```bash
#!/bin/bash

for w in $(xdotool search --name '^AI2-Thor$'); do 
    xdotool windowminimize "$w" 
done

**Comment by Lucaweihs** [comment]
Hi @GracefulMan,

Did @ekolve's suggestion work for you? The FPS rates you're getting (~300) seem quite reasonable for a single GPU. The highest FPS we managed (with an 8 GPU machine) is around 1200 FPS for navigation.
